### ISSUE TITLE
instanced-cluster with a helper-backed baseGeometry generates a call to an undefined function

### ISSUE THREAD

**Issue by gn01763009** [img2threejs/img2threejs#51]
## Summary

`generate_threejs_factory.py` emits a call to a helper it never emits when a component's `primitive` is `instanced-cluster` and its `geometryDescriptor.baseGeometry` is one of the helper-backed primitives. The generated `.ts` file references an undefined function, so `tsc` / `next build` fails on the produced factory.

## Root cause

The two sides disagree about what counts as a "used primitive".

**Call-site emission recurses through `instanced-cluster`** — `geometry_for()` resolves the cluster's base shape and re-dispatches on it (`forge/stage3_build/generate_threejs_factory.py:293-300`):

```python
if primitive == "instanced-cluster":
    base = descriptor.get("baseGeometry") if isinstance(descriptor.get("baseGeometry"), str) else "box"
    if base in ("instanced-cluster", "") or base not in VALID_PRIMITIVES:
        base = "box"
    return geometry_for(base, component)
```

So a component with `primitive: "instanced-cluster"`, `baseGeometry: "tube"` produces `buildTubeGeometry({...})`.

**Helper emission does not recurse** — it reads only the top-level `primitive` (`:351`):

```python
used_primitives = {str(component.get("primitive")) for component in components}
...
if "tube" in used_primitives:
    # emit function buildTubeGeometry(...)
```

`"tube"` never enters that set, so the helper is omitted while the call is emitted.

## Affected primitives

Any `instanced-cluster` whose `baseGeometry` is helper-backed: `extrude`, `ground-blade`, `lathe`, `tube`, `curve-sweep`.

## Reproduction

A Sculpt Spec component shaped like this is enough:

```json
{
  "id": "feathering",
  "primitive": "instanced-cluster",
  "geometryDescriptor": {
    "baseGeometry": "tube",
    "tubePath": { "points": [[0,0.1,0],[0,-0.02,0.01],[0,-0.1,0.02]], "radius": 0.004, "closed": false }
  }
}
```

Generated output contains `: buildTubeGeometry({...});` with no `function buildTubeGeometry(` anywhere in the file.

```
error TS2304: Cannot find name 'buildTubeGeometry'.
```

Encountered in the wild on a Border Collie model — a leg/tail feathering component correctly modelled as an instanced cluster of tube strands. The generated factory compiled fine in isolation but broke the host Next.js project's build, which is how it surfaced.

## Suggested fix

Make helper gating resolve `instanced-cluster` the same way `geometry_for()` does, so the two stay in agreement:

```python
def _resolved_primitives(component: dict[str, Any]) -> set[str]:
    primitive = str(component.get("primitive"))
    resolved = {primitive}
    if primitive == "instanced-cluster":
        descriptor = component.get("geometryDescriptor")
        descriptor = descriptor if isinstance(descriptor, dict) else {}
        base = descriptor.get("baseGeometry")
        if not isinstance(base, str) or base in ("instanced-cluster", "") or base not in VALID_PRIMITIVES:
            base = "box"
        resolved.add(base)
    return resolved

used_primitives = set().union(*(_resolved_primitives(c) for c in components)) if components else set()
```

This keeps the property the existing comment at `:345-350` cares about — only emitting helpers that are actually reachable, so `noUnusedLocals` builds still pass — while closing the gap.

Duplicating the resolution logic in two places is what allowed them to drift; extracting it into one helper that both `geometry_for()` and the gating call would prevent a recurrence.

## Test gap

`forge/tests/test_pipeline.py:302` covers the direct case:

```python
for primitive, builder in (("lathe", "buildLatheGeometry"), ("tube", "buildTubeGeometry")):
```

but never the indirection through `instanced-cluster`. A case with `primitive: "instanced-cluster"` + `baseGeometry: "tube"` asserting `"function buildTubeGeometry("` is present would have caught this.

## Environment

img2threejs at `c9077d5`. Consumer project: Next.js 16 / TypeScript 5, building the generated factory as part of the app.
